### ISSUE TITLE
Alpine 3.17 breaks SQL connection for ASP.NET Core: Timeout period elapsed prior to obtaining a connection from the pool

### ISSUE THREAD

**Issue by Gua-naiko-che** [alpinelinux/docker-alpine#308]
I recently tried to update the base Docker image for a ASP.NET Core 6.0 application

- Previous Docker image:  [6.0-alpine3.16](https://github.com/dotnet/dotnet-docker/blob/418f594a71bab25b021f13ced2676752089bc0b5/src/aspnet/6.0/alpine3.16/amd64/Dockerfile)
- Updated Docker image: [6.0-alpine3.17](https://github.com/dotnet/dotnet-docker/blob/418f594a71bab25b021f13ced2676752089bc0b5/src/aspnet/6.0/alpine3.17/amd64/Dockerfile)

As you can see, the only change is the alpine base image from 3.16 to 3.17.

With this, I get the following exception when tying to connect to an SQL Server database:
```
System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
```
I thought that it was maybe caused by https://github.com/dotnet/dotnet-docker/issues/4332, but I tried the solution suggested in https://github.com/dotnet/dotnet-docker/issues/4332#issuecomment-1384196212 and it does not fix the issue.

**Comment by Gua-naiko-che** [comment]
I found that updating a reference from `System.Data.SqlClient` to `Microsoft.Data.SqlClient` fixed the issue.

**Comment by LMSSonos** [comment]
@Gua-naiko-che did you find a way to solve this? I have the same issue

**Comment by Gua-naiko-che** [comment]
I didn't find a way to solve it, I stayed in the 3.16 version.

**Comment by fossdd** [comment]
Can you plase open a issue on the aports repository? https://gitlab.alpinelinux.org/alpine/aports/-/issues
