### ISSUE TITLE
Java app unable to resolve DNS , alpine 3.19

### ISSUE THREAD

**Issue by debadutta24** [alpinelinux/docker-alpine#432]
In alpine 3.19, nslookup is working but when we try to resolve DNS from our application, it throws an exception.

2024-11-21 02:06:10,557 main ERROR Unable to invoke factory method in class com.imi.dvp.vxi.notify.common.DVPKafkaAppender for element DVPKafkaAppender: java.lang.RuntimeException: java.net.UnknownHostException: [ip-172-19-30-189.proeu.imiconnect.com](https://ip-172-19-30-189.proeu.imiconnect.com/): [ip-172-19-30-189.proeu.imiconnect.com](https://ip-172-19-30-189.proeu.imiconnect.com/): Name has no usable address java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:138)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1047)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1039)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:651)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:249)
	
When I set 

dnsConfig:
  options:
    - name: ndots
      value: "1"
      
It works properly. Is this expected behaviour ?

**Comment by fossdd** [comment]
If nsloopup is working, maybe this is a bug in your application? We would need a [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) to debug this further.
